FROM 'gabetbd/ion:1.0.5'

COPY mainnet-core-config.json config/mainnet-core-config.json
COPY mainnet-core-versioning.json config/mainnet-core-versioning.json

ENV ION_CORE_CONFIG_FILE_PATH=/config/docker-mainnet-core-config.json
ENV ION_CORE_VERSIONING_CONFIG_FILE_PATH=/config/mainnet-core-versioning.json